services:
  cleanup:
    entrypoint:
      - /bin/rm
      - -fr
      - dist
      - src/biblionix.egg-info
    image: ghcr.io/williamjacksn/biblionix-dev
    init: true
    volumes:
      - ./:/home/python/python-biblionix
    working_dir: /home/python/python-biblionix

  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.12
    init: true
    volumes:
      - ./:/home/python/python-biblionix
    working_dir: /home/python/python-biblionix

  py-build:
    entrypoint:
      - /home/python/venv/bin/python
      - -m
      - build
    image: ghcr.io/williamjacksn/biblionix-dev
    init: true
    volumes:
      - ./:/home/python/python-biblionix
    working_dir: /home/python/python-biblionix

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/biblionix-dev
    init: true
    volumes:
      - ./:/home/python/python-biblionix
    working_dir: /home/python/python-biblionix
