name: Build the helper image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  image_name: ghcr.io/williamjacksn/biblionix-dev

jobs:
  build:
    name: Build the helper image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: |
            ${{ env.image_name }}
          load: true
          tags: ${{ env.image_name }}

      - name: Log in to GitHub container registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          password: ${{ github.token }}
          username: ${{ github.actor }}

      - name: Push latest image to registry
        if: github.event_name == 'push'
        run: docker image push ${{ env.image_name }}
